---
# This playbook deploys the whole application stack in this site.

# ansible-playbook sites.yml -i hosts --connection=local

# Apply common configuration to all hosts
- hosts: all
  sudo: yes
  roles:
  - common
  - ntp

# Apply common configuration the build host
- hosts: build
  roles:
  - common
  - ntp
  - php
  - build

# Configure and deploy database servers.
- hosts: dbservers
  user: root
  roles:
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers
  user: root
  roles:
  - base-apache
  - php
  - newrelic
  - environment

# Configure and deploy the load balancer(s).
- hosts: loadbalancers
  user: root
  roles:
  - varnish
  - haproxy

# Configure and deploy the Nagios monitoring node(s).
- hosts: monitoring
  user: root
  roles:
  - base-apache
  - nagios

  # Configure and deploy the build node(s).
- hosts: build
  user: root
  roles:
  - php