---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: RedHat | Add the New Relic repository key
  copy:
    src: RPM-GPG-KEY-NewRelic
    dest: /etc/pki/rpm-gpg
    owner: root
    group: root
    mode: 0644

- name: RedHat | Add the Rew Relic repository file
  copy:
    src: newrelic.repo
    dest: /etc/yum.repos.d/newrelic.repo
    owner: root
    group: root
    mode: 0644

- name: RedHat | Install New Relic PHP
  yum:
    name: newrelic-php5
    state: latest
  notify:
    - restart newrelic

- name: RedHat | Install New Relic Sysmond
  yum:
    name: newrelic-sysmond
    state: latest
  notify:
    - Restart New Relic

- name: Configure New Relic Sysmond
  template:
    src: nrsysmond.cfg.j2
    dest: /etc/newrelic/nrsysmond.cfg
    group: newrelic
    owner: root
    mode: 0640
  notify:
    - restart newrelic

- name: Ensure New Relic Sysmond is started and enabled
  service:
    name: newrelic-sysmond
    state: started
    enabled: yes
