---
galaxy_info:
  author: Björn Dieding
  description: Install and configure the New Relic System Monitor Daemon
  license: GPL
  min_ansible_version: 1.4
  platforms:
    - name: EL
      versions:
        - 7
  categories:
    - monitoring
dependencies: []
